version: '3'

services:

  nodejs:
    image: node:13-slim
    container_name: nodejs
    working_dir: /app
    command: yarn start
    ports: ['3000:3000']
    volumes: 
      - .:/app
    links:
      - api

  api:
    build: ./docker/api
    container_name: api
    ports: ['8000:8000']
    volumes: 
      - ./api:/app